# tools/github_feedback_tool.py

import os
import json
from dotenv import load_dotenv
from github import Github, Auth
import google.generativeai as genai

load_dotenv("/usr/local/google/home/bmajumdar/Glovo_githubPR/.env")

class FeedbackExtractor:
    def __init__(self, repo_name: str, pr_number: int):
        self.project_id = os.getenv("GCP_PROJECT_ID")
        self.secret_id = os.getenv("SECRET_ID")
        self.secret_version = os.getenv("SECRET_VERSION", "latest")
        self.repo_name = repo_name
        self.pr_number = pr_number
        self.gemini_api_key = os.getenv("GEMINI_API_KEY")
        
        # Access token via Secret Manager or fallback
        self.token = self._resolve_token()
        
        auth = Auth.Token(self.token)
        self.g = Github(auth=auth)
        self.repo = self.g.get_repo(self.repo_name)
        self.pr = self.repo.get_pull(self.pr_number)
        
        genai.configure(api_key=self.gemini_api_key)
        self.model = genai.GenerativeModel("gemini-1.5-flash")

    def _resolve_token(self) -> str:
        try:
            from google.cloud import secretmanager
            client = secretmanager.SecretManagerServiceClient()
            name = f"projects/{self.project_id}/secrets/{self.secret_id}/versions/{self.secret_version}"
            response = client.access_secret_version(request={"name": name})
            return response.payload.data.decode("UTF-8").strip()
        except Exception:
            return os.getenv("GITHUB_TOKEN", "").strip()


    def _get_comments(self) -> list:
        """Retrieves raw comments from both inline reviews and general conversation."""
        extracted = []
        
        # 1. Fetch inline review comments (associated with specific code hunks)
        review_comments = self.pr.get_review_comments()
        for comment in review_comments:
            extracted.append({
                "type": "inline",
                "path": comment.path,
                "body": comment.body,
                "diff_hunk": comment.diff_hunk,
                "comment_id": comment.id
            })
            
        # 2. Fetch general PR comments
        issue_comments = self.pr.get_issue_comments()
        for comment in issue_comments:
            extracted.append({
                "type": "general",
                "path": "General PR Scope",
                "body": comment.body,
                "diff_hunk": None,
                "comment_id": comment.id
            })
            
        return extracted

    def parse_feedback_with_llm(self, comment_data: dict) -> dict:
        """Translates unstructured developer feedback into logical constraints."""
        prompt = f"""
        You are an elite software architect parsing developer code reviews.
        Analyze the following feedback and output a clean JSON object.

        Context:
        - Target File: {comment_data['path']}
        - Code Diff Context: {comment_data['diff_hunk']}
        - Reviewer Comment: {comment_data['body']}

        Respond with valid JSON matches this schema:
        {{
            "identified_error": "Description of what was rejected or failed",
            "affected_file": "File path or 'global'",
            "remediation_plan": "Actionable, precise step-by-step instructions to prevent this issue in subsequent generations"
        }}
        Do not wrap the JSON output in backticks or markdown markers. Return ONLY the raw JSON string.
        """
        try:
            response = self.model.generate_content(prompt)
            # Remove potential markdown wraps if LLM adds them
            cleaned_text = response.text.replace("```json", "").replace("```", "").strip()
            return json.loads(cleaned_text)
        except Exception as e:
            return {
                "identified_error": "Failed to parse feedback",
                "affected_file": comment_data['path'],
                "remediation_plan": f"Review comment manually: {comment_data['body']}. Raw error: {str(e)}"
            }

    def process(self) -> list:
        """Retrieves all feedback and returns structured remediation profiles."""
        raw_comments = self._get_comments()
        structured_feedback = []
        for comment in raw_comments:
            # Skip comments generated by bot to avoid feedback loops
            if "[Caretta]" in comment["body"] or "automated" in comment["body"]:
                continue
            parsed = self.parse_feedback_with_llm(comment)
            parsed["comment_id"] = comment["comment_id"]
            parsed["pr_number"] = self.pr_number
            structured_feedback.append(parsed)
        return structured_feedback

def extract_pr_feedback(pr_number: int) -> str:
    """
    Analyzes developer feedback on a target pull request and returns 
    structured architectural constraints.
    """
    repo_name = os.getenv("GITHUB_REPO")
    if not repo_name:
        return "Error: GITHUB_REPO not defined in environment."
    
    try:
        extractor = FeedbackExtractor(repo_name, pr_number)
        feedback_list = extractor.process()
        return json.dumps(feedback_list, indent=2)
    except Exception as e:
        return f"Failed to retrieve or process PR feedback: {str(e)}"